# Generated by Django 2.1.7 on 2019-02-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(default='body'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='url'),
        ),
    ]
